import React, { useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { BackgroundLayer } from '@/components/BackgroundLayer';
import { AppButton } from '@/components/AppButton';
import { MockNotice, PageHeader, SectionCard, StatusPill } from '@/components/ProductUI';
import { spacing, typography } from '@/constants/colors';
export default function DataExport(){const colors=useColors();const insets=useSafeAreaInsets();const [state,setState]=useState<'idle'|'submitted'|'processing'|'ready'|'failed'>('idle');return <View style={[styles.root,{backgroundColor:colors.background,paddingTop:Platform.OS==='web'?40:insets.top}]}><BackgroundLayer/><PageHeader title="Export Your Data" subtitle="Portable account copy"/><View style={styles.content}><View style={[styles.icon,{backgroundColor:colors.primary+'18'}]}><Feather name="download-cloud" size={42} color={colors.primary}/></View><Text style={[styles.title,{color:colors.foreground}]}>{state==='idle'?'Request an export':state==='ready'?'Your export is ready':state==='failed'?'Export needs attention':'Export requested'}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>The export is expected to include profile, preferences, workouts, nutrition entries, bookings and messages where legally available. Final scope and retention require legal approval.</Text><SectionCard title="Request status"><StatusPill label={state==='idle'?'Not requested':state} tone={state==='ready'?'success':state==='failed'?'danger':'warning'}/>{state!=='idle'&&<Text style={[styles.body,{color:colors.mutedForeground}]}>Reference: EXP-PREVIEW-2026 · updates will appear in notifications.</Text>}</SectionCard>{state==='idle'?<AppButton label="Request Export" onPress={()=>setState('submitted')}/>:state==='submitted'?<AppButton label="Preview Processing" onPress={()=>setState('processing')}/>:state==='processing'?<AppButton label="Preview Ready State" onPress={()=>setState('ready')}/>:state==='ready'?<AppButton label="Download Secure File (Preview)" onPress={()=>{}}/>:<AppButton label="Try Again" onPress={()=>setState('submitted')}/>}<MockNotice>Secure export generation, identity verification, expiring downloads and delivery are pending Milestone 2.</MockNotice></View></View>}
const styles=StyleSheet.create({root:{flex:1},content:{flex:1,justifyContent:'center',padding:spacing.xl,gap:spacing.lg},icon:{width:88,height:88,borderRadius:44,alignSelf:'center',alignItems:'center',justifyContent:'center'},title:{...typography.hero,textAlign:'center'},body:{...typography.body,textAlign:'center'}});
