import React, { useMemo, useState } from 'react';
import { FlatList, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { BackgroundLayer } from '@/components/BackgroundLayer';
import { PageHeader, SearchField, StatusPill } from '@/components/ProductUI';
import { radii, spacing, typography } from '@/constants/colors';

type Notice={id:string;title:string;body:string;time:string;icon:string;category:string;read:boolean};
const initial:Notice[]=[
  {id:'n1',title:'Workout ready',body:'Your next active-program session is ready to start.',time:'10 min ago',icon:'dumbbell',category:'Training',read:false},
  {id:'n2',title:'Session reminder',body:'Your coaching session starts tomorrow at 10:00 AM.',time:'2 hr ago',icon:'video-outline',category:'Coaching',read:false},
  {id:'n3',title:'Hydration goal',body:'You are one glass away from today’s hydration target.',time:'Yesterday',icon:'water-outline',category:'Nutrition',read:true},
  {id:'n4',title:'Streak protected',body:'You maintained your consistency streak this week.',time:'Mon',icon:'fire',category:'Achievement',read:true},
];
export default function NotificationCenter(){const colors=useColors();const insets=useSafeAreaInsets();const [items,setItems]=useState(initial);const [q,setQ]=useState('');const filtered=useMemo(()=>items.filter(n=>(n.title+n.body+n.category).toLowerCase().includes(q.toLowerCase())),[items,q]);return <View style={[styles.root,{backgroundColor:colors.background,paddingTop:Platform.OS==='web'?40:insets.top}]}><BackgroundLayer/><PageHeader title="Notifications" subtitle={`${items.filter(i=>!i.read).length} unread`} right={<Pressable onPress={()=>setItems(v=>v.map(i=>({...i,read:true})))} style={styles.mark} accessibilityRole="button" accessibilityLabel="Mark all notifications read"><Text style={{color:colors.primary}}>Read all</Text></Pressable>}/><View style={styles.search}><SearchField value={q} onChangeText={setQ} placeholder="Search notifications" /></View><FlatList data={filtered} keyExtractor={i=>i.id} contentContainerStyle={[styles.list,{paddingBottom:insets.bottom+24}]} ListEmptyComponent={<View style={styles.empty}><MaterialCommunityIcons name="bell-check-outline" size={42} color={colors.mutedForeground}/><Text style={[styles.emptyTitle,{color:colors.foreground}]}>You’re all caught up</Text><Text style={[styles.emptyBody,{color:colors.mutedForeground}]}>New training, coaching and account updates will appear here.</Text></View>} renderItem={({item})=><Pressable onPress={()=>setItems(v=>v.map(n=>n.id===item.id?{...n,read:true}:n))} style={[styles.item,{backgroundColor:item.read?colors.card:colors.primary+'12',borderColor:item.read?colors.border:colors.primary+'55'}]} accessibilityRole="button" accessibilityLabel={`${item.read?'Read':'Unread'} notification: ${item.title}`}><View style={[styles.icon,{backgroundColor:colors.primary+'18'}]}><MaterialCommunityIcons name={item.icon as any} size={22} color={colors.primary}/></View><View style={{flex:1}}><View style={styles.top}><Text style={[styles.title,{color:colors.foreground}]}>{item.title}</Text>{!item.read&&<View style={[styles.dot,{backgroundColor:colors.primary}]}/>}</View><Text style={[styles.body,{color:colors.mutedForeground}]}>{item.body}</Text><View style={styles.meta}><StatusPill label={item.category} tone="muted"/><Text style={[styles.time,{color:colors.mutedForeground}]}>{item.time}</Text></View></View></Pressable>}/></View>}
const styles=StyleSheet.create({root:{flex:1},mark:{minWidth:64,height:44,alignItems:'center',justifyContent:'center'},search:{padding:spacing.md,paddingBottom:0},list:{padding:spacing.md,gap:spacing.sm},item:{borderWidth:1,borderRadius:radii.lg,padding:spacing.md,flexDirection:'row',gap:spacing.sm},icon:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},top:{flexDirection:'row',alignItems:'center',gap:8},title:{...typography.label,flex:1},body:{...typography.bodySmall,marginTop:4},dot:{width:8,height:8,borderRadius:4},meta:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:spacing.sm},time:{...typography.caption},empty:{padding:48,alignItems:'center',gap:spacing.sm},emptyTitle:{...typography.title},emptyBody:{...typography.bodySmall,textAlign:'center'}});
