import React, { useState } from 'react';
import { Platform, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { BackgroundLayer } from '@/components/BackgroundLayer';
import { InfoRow, MockNotice, PageHeader, SectionCard, StatusPill } from '@/components/ProductUI';
import { spacing, typography } from '@/constants/colors';

export default function PrivacyControls(){const colors=useColors();const insets=useSafeAreaInsets();const [health,setHealth]=useState(true);const [analytics,setAnalytics]=useState(false);const [marketing,setMarketing]=useState(false);const Toggle=({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void})=><View style={styles.toggle}><Text style={[styles.toggleText,{color:colors.foreground}]}>{label}</Text><Switch value={value} onValueChange={set} trackColor={{true:colors.primary,false:colors.muted}} accessibilityLabel={label}/></View>;return <View style={[styles.root,{backgroundColor:colors.background,paddingTop:Platform.OS==='web'?40:insets.top}]}><BackgroundLayer/><PageHeader title="Privacy & Data" subtitle="Control your information"/><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+24}]}><SectionCard title="Consent preferences" subtitle="Legal wording and consent version require approval before production."><Toggle label="Use health data for FP Score" value={health} set={setHealth}/><Toggle label="Optional product analytics" value={analytics} set={setAnalytics}/><Toggle label="Marketing communications" value={marketing} set={setMarketing}/><StatusPill label="Saved locally for preview" tone="muted"/></SectionCard><SectionCard title="Your data"><InfoRow icon="archive-arrow-down-outline" label="Request data export" value="Prepare a portable copy of your account data" onPress={()=>router.push('/data-export')}/><InfoRow icon="account-remove-outline" label="Delete account" value="Review consequences and submit a deletion request" danger onPress={()=>router.push('/delete-account')}/><InfoRow icon="shield-account-outline" label="Privacy policy" value="Review how Foster Performance handles data" onPress={()=>router.push('/privacy-policy')}/></SectionCard><SectionCard title="Account controls"><InfoRow icon="devices" label="Active sessions" value="Sign out other devices from Profile → Security"/><InfoRow icon="bell-outline" label="Notification permission" value="Managed in notification preferences" onPress={()=>router.push('/notifications')}/></SectionCard><MockNotice>Consent persistence, data export generation and deletion processing require Milestone 2 privacy endpoints.</MockNotice></ScrollView></View>}
const styles=StyleSheet.create({root:{flex:1},content:{padding:spacing.md,gap:spacing.md},toggle:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},toggleText:{...typography.label,flex:1}});
