const colors = {
  light: {
    text: '#0a0a0a',
    tint: '#2F80FF',
    background: '#F4F4F4',
    foreground: '#0A0A0A',
    card: '#FFFFFF',
    cardForeground: '#0A0A0A',
    primary: '#2F80FF',
    primaryForeground: '#FFFFFF',
    secondary: '#F0F0F0',
    secondaryForeground: '#1A1A1A',
    muted: '#EFEFEF',
    mutedForeground: '#666666',
    accent: '#D6A84B',
    accentForeground: '#0A0A0A',
    success: '#35C98A',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#E0E0E0',
    input: '#E0E0E0',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#2F80FF',
    background: '#05070B',
    foreground: '#FFFFFF',
    card: '#0D1117',
    cardForeground: '#FFFFFF',
    primary: '#2F80FF',
    primaryForeground: '#FFFFFF',
    secondary: '#12151C',
    secondaryForeground: '#FFFFFF',
    muted: '#12151C',
    mutedForeground: '#9AA3B5',
    accent: '#D6A84B',
    accentForeground: '#0A0A0A',
    success: '#35C98A',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#141720',
    input: '#141720',
  },
  radius: 12,
};

export default colors;
