import React, { useState } from 'react';
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { RoleGate } from '@/components/RoleGate';
import { BackgroundLayer } from '@/components/BackgroundLayer';
import { AppButton } from '@/components/AppButton';
import { InfoRow, MockNotice, PageHeader, SectionCard, StatusPill } from '@/components/ProductUI';
import { radii, spacing, typography } from '@/constants/colors';

export default function CoachClientDetail(){const {id}=useLocalSearchParams<{id:string}>();const colors=useColors();const insets=useSafeAreaInsets();const [note,setNote]=useState('');const [notes,setNotes]=useState(['Focus on controlled tempo during lower-body work.']);const [assigned,setAssigned]=useState('Strength & Conditioning');return <RoleGate allow={['coach']}><View style={[styles.root,{backgroundColor:colors.background,paddingTop:Platform.OS==='web'?40:insets.top}]}><BackgroundLayer/><PageHeader title="Client Detail" subtitle="Coaching workspace · privacy limited"/><ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+24}]}><SectionCard><View style={styles.hero}><View style={[styles.avatar,{backgroundColor:colors.primary+'20'}]}><Text style={[styles.avatarText,{color:colors.primary}]}>CL</Text></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.foreground}]}>Client {id}</Text><Text style={[styles.meta,{color:colors.mutedForeground}]}>Active coaching client · member contact protected</Text></View><StatusPill label="Active" tone="success"/></View></SectionCard><SectionCard title="Sessions"><InfoRow icon="calendar-clock" label="Upcoming session" value="Thu, Aug 27 · 10:00 AM · 60 min"/><InfoRow icon="history" label="Previous sessions" value="4 completed · last session Aug 20"/><InfoRow icon="message-outline" label="Message client" value="Open the existing approved conversation" onPress={()=>router.push('/messages')}/></SectionCard><SectionCard title="Program assignment"><InfoRow icon="clipboard-check-outline" label={assigned||'No assigned program'} value={assigned?'Assigned · week 2 preview':'Choose an approved coach program'}/><View style={styles.actions}><AppButton label="Assign Program" style={{flex:1}} onPress={()=>setAssigned('8-Week Performance Builder')}/><AppButton label="Remove" variant="secondary" style={{flex:1}} disabled={!assigned} onPress={()=>setAssigned('')}/></View></SectionCard><SectionCard title="Private coach notes" subtitle="Only the coach and authorized staff should access these notes.">{notes.map((n,i)=><View key={i} style={[styles.noteCard,{backgroundColor:colors.muted}]}><Text style={[styles.noteText,{color:colors.foreground}]}>{n}</Text><Text style={[styles.noteMeta,{color:colors.mutedForeground}]}>Preview · just now</Text></View>)}<TextInput value={note} onChangeText={setNote} placeholder="Add a coaching note" placeholderTextColor={colors.mutedForeground} multiline style={[styles.input,{color:colors.foreground,backgroundColor:colors.muted,borderColor:colors.border}]}/><AppButton label="Save Note" disabled={!note.trim()} onPress={()=>{setNotes(v=>[...v,note.trim()]);setNote('')}}/></SectionCard><MockNotice>Client relationships, assignments, notes authorization and persistence require Milestone 2 APIs.</MockNotice></ScrollView></View></RoleGate>}
const styles=StyleSheet.create({root:{flex:1},content:{padding:spacing.md,gap:spacing.md},hero:{flexDirection:'row',alignItems:'center',gap:spacing.sm},avatar:{width:56,height:56,borderRadius:28,alignItems:'center',justifyContent:'center'},avatarText:{...typography.title},name:{...typography.title},meta:{...typography.bodySmall,marginTop:2},actions:{flexDirection:'row',gap:spacing.sm},noteCard:{padding:spacing.sm,borderRadius:radii.md,gap:4},noteText:{...typography.bodySmall},noteMeta:{...typography.caption},input:{minHeight:90,borderWidth:1,borderRadius:radii.md,padding:spacing.sm,textAlignVertical:'top',...typography.body}});
